# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_register(object):
    def setupUi(self, register_2):
        register_2.setObjectName("register_2")
        register_2.resize(360, 186)
        self.layoutWidget = QtWidgets.QWidget(register_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 341, 184))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lab_nickname = QtWidgets.QLabel(self.layoutWidget)
        self.lab_nickname.setObjectName("lab_nickname")
        self.horizontalLayout.addWidget(self.lab_nickname)
        spacerItem = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.line_nickname = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_nickname.setObjectName("line_nickname")
        self.horizontalLayout.addWidget(self.line_nickname)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(5, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lab_password = QtWidgets.QLabel(self.layoutWidget)
        self.lab_password.setObjectName("lab_password")
        self.horizontalLayout_2.addWidget(self.lab_password)
        spacerItem2 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.line_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_password.setObjectName("line_password")
        self.horizontalLayout_2.addWidget(self.line_password)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lab_reenter = QtWidgets.QLabel(self.layoutWidget)
        self.lab_reenter.setObjectName("lab_reenter")
        self.horizontalLayout_4.addWidget(self.lab_reenter)
        spacerItem3 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.line_reenter = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_reenter.setObjectName("line_reenter")
        self.horizontalLayout_4.addWidget(self.line_reenter)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.but_register = QtWidgets.QPushButton(self.layoutWidget)
        self.but_register.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.but_register.setObjectName("but_register")
        self.horizontalLayout_3.addWidget(self.but_register)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.but_cancel = QtWidgets.QPushButton(self.layoutWidget)
        self.but_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.but_cancel.setObjectName("but_cancel")
        self.horizontalLayout_3.addWidget(self.but_cancel)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.listWidget = QtWidgets.QListWidget(register_2)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 361, 191))
        self.listWidget.setStyleSheet("border-image: url(:/images/background.png);")
        self.listWidget.setObjectName("listWidget")
        self.listWidget.raise_()
        self.layoutWidget.raise_()
        self.retranslateUi(register_2)
        self.but_cancel.clicked.connect(register_2.close)
        QtCore.QMetaObject.connectSlotsByName(register_2)

    def retranslateUi(self, register_2):
        _translate = QtCore.QCoreApplication.translate
        register_2.setWindowTitle(_translate("register_2", "Register"))
        self.lab_nickname.setText(_translate("register_2", "Nickname"))
        self.lab_password.setText(_translate("register_2", "Password"))
        self.lab_reenter.setText(_translate("register_2", "Re-enter"))
        self.checkBox.setText(_translate("register_2", "I agree NEUrules"))
        self.but_register.setText(_translate("register_2", "Register"))
        self.but_cancel.setText(_translate("register_2", "Cancel"))

import resource
